name: Close Jira issue

on:
  issues:
    types: [closed]

jobs:
  close-issue:
    name: Close linked Jira issue
    runs-on: ubuntu-latest

    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Extract JIRA issue key from title
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          JIRA_KEY=$(echo "$ISSUE_TITLE" | grep -oE '[A-Z]+-[0-9]+' || echo "")
          if [[ -z "$JIRA_KEY" ]]; then
            echo "❌ Jira 키가 제목에 없습니다. 워크플로 종료."
            exit 0
          fi
          echo "JIRA_KEY=$JIRA_KEY" >> $GITHUB_ENV

      - name: Transition Jira issue to Done
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.JIRA_KEY }}
          transition: Done  # 또는 Jira 설정에 맞는 상태 이름 (예: 완료, 완료됨, 해결 등)
