name: CI/CD to Raspberry Pi

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build Docker & Push
        run : |
          sudo docker run -d --name odo \
          -p 8080:8080 \
          -e SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
          -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
          -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
          -e JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }} \
          ${{ secrets.DOCKER_REPO }}:latest
  

      - name: Deploy to Raspberry Pi
        uses : appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo rm odo.log || true &&
            docker stop odo || true &&
            docker rm odo || true &&
            sudo docker run -d --name odo -p 8080:8080 -d ${{ secrets.DOCKER_REPO }}:latest .
            sudo docker logs -f odo &> odo.log &
            docker image prune -f